In [1]:
from functions import *
import glob

## Load test and train data

In [2]:
def load_data(train_ids, test_ids):
    train_data = {}
    test_data = {}
    
    for i in train_ids:
        train_data[i] = {}
        path = "train_data/user_{}/final_data/".format(i)
        dataframes = []
        for file in glob.glob(path + "/*"):
            dataframes.append(pd.read_csv(file))

        train_data[i]['data'] = pd.concat([i for i in dataframes])
        train_data[i]['X'] = train_data[i]['data'][:]
        train_data[i]['y'] = train_data[i]['X'].pop('user')
        
    for i in test_ids:
        test_data[i] = {}
        path = "test_data/user_{}/final_data/".format(i)
        file = path + last_csv_file(path)
        
        test_data[i]['file'] = file
        test_data[i]['data'] = pd.read_csv(file)
        test_data[i]['X'] = test_data[i]['data'][:]
        test_data[i]['y'] = test_data[i]['X'].pop('user')
        
    return train_data, test_data
    

In [3]:
train_ids = [0, 1, 2]
test_ids = [0, 1, 2, 3, 4]

train_data, test_data = load_data(train_ids, test_ids)

In [4]:
X_all_train = pd.concat([train_data[i]['X'] for i in train_ids])
y_all_train = pd.concat([train_data[i]['y'] for i in train_ids])

## SVM

In [5]:
test_data[2]['file']

'test_data/user_2/final_data/5.csv'

In [6]:
clf = svm.OneClassSVM(nu=0.1, kernel="rbf", gamma=0.001)
clf.fit(train_data[2]['X'])
y_test_pred = clf.predict(test_data[2]['X'])
unique, counts = np.unique(y_test_pred, return_counts=True)
counts_dict = dict(zip(unique, counts))
if 1 in counts_dict:
    match = (counts_dict[1] / len(y_test_pred)) * 100
else:
    match = 0

print(match)

80.0


## MLP

In [7]:
from sklearn.neural_network import MLPClassifier

In [8]:
clf = MLPClassifier().fit(X_all_train, y_all_train)

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/neural_network/multilayer_perceptron.py:562: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [16]:
for i in test_ids:
    print(i, clf.predict(test_data[i]['X']))

0 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
1 [1. 1. 1. 1. 1. 1. 1. 1. 1.]
2 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
3 [0. 0. 0. 0. 0. 0. 0. 0. 0.]
4 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


## KNN

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
clf = KNeighborsClassifier().fit(X_all_train, y_all_train)

In [15]:
for i in test_ids:
    print(clf.predict(test_data[i]['X']))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
[0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
